---
title: "Lab_2"
output: html_notebook
---
  
```{r}
library(nycflights13)
library(dplyr)


flights <- nycflights13::flights
airports <- nycflights13::airports
planes <- nycflights13::planes
airlines <- nycflights13::airlines
weather <- nycflights13::weather

flights
airports
planes
airlines
weather

```


1. Inner-join

```{r}



#1.1. Conecte fligths con planes
flights_planes_joined <- flights %>%
  inner_join(planes, by = "tailnum")

#1.2. Conecte fligths con airlines
flights_airlines_joined <- flights %>%
  inner_join(airlines, by = "carrier")

#1.3. Conecte fligths con airports (según el esquema de arriba existe una doble relación de
#airports hacía fligths)

flights
airports

flights_airports_joined <- airports %>%
  inner_join(flights, by = c("faa"="origin")) %>%
inner_join(flights, by = c("faa"="dest"))

#1.4. Conecte flights con weather (según esquema de arriba, hay 5 variables que relacionan
#a ambas tablas)
flights %>%
  inner_join(weather, by = c("origin","year","month","day","hour"))


```

2. Data manipulation


```{r}

#2.1. Utilice el verbo count en flights y envíe como parámetro las variables year, month, day.
#Luego filtre n para que sea mayor a 1000. Por último ordene n con el verbo arrange y
#devuelva el resultado.

arranged_flights <- flights  %>%
  count(year, month, day) %>%
  filter(n>1000) %>%
  arrange(desc(n))

arranged_flights 

```
```{r}
#2.2. Utilice el concepto de selección por rango (aplicando el operador “:”) para obtener las
#variables year hacia day. También agregue a esta selección hour, origin, dest, tailnum,
#carrier, arr_delay, dep_delay, por último almacene el resultado en la variable
#flights_selected.

flights_selected <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier, arr_delay, dep_delay)
flights_selected

```
```{r}

#2.3. Utilice left_join para combinar airlines y flights_selected. Al obtener el resultado, utilice
#el verbo select para eliminar las columnas origin y dest (utilice el operador “-” para
#descartar estas columnas únicamente). Por último agregue una nueva columna con el
#verbo mutate, asigne el nombre tot_delay y opere la suma de arr_delay y dep_delay
flights_selected
airlines

Total_delay_of_planes <- flights_selected %>%
  left_join(airlines, by ="carrier") %>%
  select(-origin, -dest)%>%
  mutate(total_delay = arr_delay +dep_delay)

Total_delay_of_planes


```

```{r}
#2.4

#Utilice inner_join para combinar flights y weather, luego agrupe por la variable precip.

#Utilice summarize para encontrar el promedio de la variable dep_delay (aplicando la función mean), asigne al promedio el nombre delay.

#Al utilizar la función mean agregue el parámetro na.rm y asígnele TRUE por defecto. 

#A continuación un ejemplo: mean(variable, na.rm = TRUE)

#Esta expresión simplemente indica a R que si encuentra valores perdidos en la variable los elimine.

flights %>%
  inner_join(weather, by = c("origin","year","month","day","hour")) %>%
  group_by(precip) %>%
  summarize()
  



```


